import { createContext, useContext, useState, useCallback } from 'react'

const LangContext = createContext(null)

const translations = {
  es: {
    dashboard: 'Panel Principal', employees: 'Empleados', attendance: 'Asistencia',
    payroll: 'Nómina', overtime: 'Horas Extra', requests: 'Solicitudes',
    schedule: 'Calendario', reports: 'Reportes', users: 'Usuarios',
    departments: 'Departamentos', onboarding: 'Onboarding', settings: 'Configuración',
    general: 'General', localization: 'Localización', security: 'Seguridad',
    profile: 'Mi Perfil', login: 'Iniciar Sesión', logout: 'Cerrar Sesión',
    save: 'Guardar', cancel: 'Cancelar', add: 'Agregar', edit: 'Editar',
    delete: 'Eliminar', search: 'Buscar', filter: 'Filtrar', export: 'Exportar',
    total: 'Total', approved: 'Aprobado', pending: 'Pendiente', rejected: 'Rechazado',
    active: 'Activo', inactive: 'Inactivo', welcome: 'Bienvenido de vuelta',
    totalEmployees: 'Total Empleados', pendingRequests: 'Solicitudes Pendientes',
    monthlyPayroll: 'Nómina Mensual', activeUsers: 'Usuarios Activos',
    thisMonth: 'este mes', newToday: 'nuevas hoy', overtimeHours: 'Horas Extra',
    byDepartment: 'Por Departamento', byUser: 'Por Usuario', totalHours: 'Total Horas',
    approvedRequests: 'Solicitudes Aprobadas', vacationDays: 'Días Vacaciones',
    recentActivity: 'Actividad Reciente', shifts: 'Turnos', generateAI: 'Generar con IA',
    weeklyHours: 'Horas esta semana', language: 'Idioma',
    name: 'Nombre', email: 'Correo', role: 'Rol', area: 'Área', status: 'Estado',
    actions: 'Acciones', date: 'Fecha', time: 'Hora', type: 'Tipo',
    description: 'Descripción', attachment: 'Adjunto', download: 'Descargar',
    close: 'Cerrar', confirm: 'Confirmar', back: 'Volver', next: 'Siguiente',
    previous: 'Anterior', loading: 'Cargando', noData: 'Sin datos',
    employee: 'Empleado', department: 'Departamento', position: 'Cargo',
    phone: 'Teléfono', address: 'Dirección', startDate: 'Fecha Inicio',
    salary: 'Salario', contract: 'Contrato', documents: 'Documentos',
    personalInfo: 'Información Personal', payrollInfo: 'Información Nómina',
    history: 'Historial', notes: 'Notas',
    dailyRecords: 'Registros Diarios', liveStats: 'Estadísticas en Vivo',
    onTime: 'A Tiempo', late: 'Tarde', absent: 'Ausente', present: 'Presente',
    checkIn: 'Entrada', checkOut: 'Salida', workedHours: 'Horas Trabajadas',
    rules: 'Reglas', costSimulator: 'Simulador de Costos',
    baseRate: 'Tarifa Hora Base', ruleToSimulate: 'Regla a Simular',
    hoursWorked: 'Horas Trabajadas', regularPay: 'Pago Regular',
    surcharge: 'Recargo', grossTotal: 'Total Bruto', result: 'Resultado',
    configuredRules: 'Reglas Configuradas', newRule: 'Nueva Regla',
    daytime: 'Diurna', nighttime: 'Nocturna', sunday: 'Dominical',
    multiplier: 'Multiplicador', shiftType: 'Tipo de Turno',
    liquidation: 'Liquidación', payrollHistory: 'Historial de Nómina',
    baseSalary: 'Salario Base', deductions: 'Deducciones', netPay: 'Pago Neto',
    bonus: 'Bonificación', socialSecurity: 'Seguridad Social',
    approve: 'Aprobar', reject: 'Rechazar', medical: 'Médica',
    vacation: 'Vacaciones', personal: 'Personal', remote: 'Remoto',
    training: 'Capacitación', requestType: 'Tipo de Solicitud',
    shiftSchedule: 'Calendario de Turnos', yearView: 'Vista anual',
    dragToCreate: 'Arrastra sobre los días para crear turnos',
    morning: 'Mañana', afternoon: 'Tarde', night: 'Noche',
    assignedShifts: 'Turnos Asignados', activeEmployees: 'Empleados Activos',
    coverage: 'Cobertura', uncovered: 'Sin Cubrir', dayDetail: 'Detalle del día',
    people: 'Personas', hours: 'Horas', noShifts: 'Sin turnos',
    assignedShiftsList: 'Turnos asignados', createShift: 'Crear Turno',
    selectEmployee: 'Seleccionar...', shiftTypeLabel: 'Tipo de Turno',
    generateWithAI: 'Generar con IA', applysuggestion: 'Aplicar sugerencia',
    discard: 'Descartar', optimizationGoal: 'Objetivo de Optimización',
    optimizeByCost: 'Optimizar por costo', reduceOpCosts: 'Reduce gastos operativos',
    shiftEquity: 'Equidad de turnos', fairDistribution: 'Distribución justa de horas',
    seniorityPriority: 'Prioridad antigüedad', preferSeniors: 'Preferencia a seniors',
    constraints: 'Restricciones', minRestHours: 'Min. horas descanso',
    minRestDesc: 'Intervalo mínimo entre turnos consecutivos.',
    avoidOvertime: 'Evitar horas extra', generating: 'Generando...',
    estimatedTime: 'Tiempo estimado: ~15 segundos',
    previewWeek: 'Vista Previa: Semana 42',
    equity: 'Equidad', cost: 'Costo',
    shiftsGenerated: 'Turnos generados exitosamente con IA',
    shiftsApplied: 'Turnos aplicados al calendario',
    overview: 'Resumen', trends: 'Tendencias', analytics: 'Analítica',
    custom: 'Personalizado', monthly: 'Mensual', weekly: 'Semanal',
    daily: 'Diario', annual: 'Anual',
    overtimeByDept: 'Horas Extra por Departamento',
    topOvertimeUsers: 'Top Horas Extra por Usuario',
    monthlyTrend: 'Tendencia Mensual',
    rolesPermissions: 'Roles y Permisos', auditLog: 'Registro de Auditoría',
    createUser: 'Crear Usuario', editUser: 'Editar Usuario',
    lastAccess: 'Último Acceso', createdAt: 'Creado',
    permission: 'Permiso', module: 'Módulo',
    addDepartment: 'Agregar Departamento', editDepartment: 'Editar Departamento',
    manager: 'Responsable', employeeCount: 'Empleados',
    step: 'Paso', personalData: 'Datos Personales', documentation: 'Documentación',
    bankInfo: 'Información Bancaria', review: 'Revisión',
    fullName: 'Nombre Completo', idNumber: 'Número de Identificación',
    birthDate: 'Fecha de Nacimiento', gender: 'Género',
    emergencyContact: 'Contacto de Emergencia',
    bankName: 'Banco', accountNumber: 'Número de Cuenta',
    accountType: 'Tipo de Cuenta', uploadDocuments: 'Subir Documentos',
    timezone: 'Zona Horaria', currency: 'Moneda', dateFormat: 'Formato de Fecha',
    twoFactorAuth: 'Autenticación de Dos Factores',
    passwordPolicy: 'Política de Contraseñas', sessionTimeout: 'Tiempo de Sesión',
    companyName: 'Nombre de Empresa', companyLogo: 'Logo de Empresa',
    primaryColor: 'Color Primario', notifications: 'Notificaciones',
    myProfile: 'Mi Perfil', changePassword: 'Cambiar Contraseña',
    currentPassword: 'Contraseña Actual', newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    mySchedule: 'Mi Horario', myRequests: 'Mis Solicitudes',
    newRequest: 'Nueva Solicitud', submitRequest: 'Enviar Solicitud',
    requestSent: 'Solicitud enviada exitosamente',
    allModules: 'Todos los módulos', employeePortal: 'Portal Empleado',
    diurnal: 'Diurnas', nocturnal: 'Nocturnas', totalCost: 'Costo Total',
    shiftsMonth: 'Turnos Mes', approvedH: 'Aprobadas',
    pendingH: 'pendientes', year: 'Año', week: 'Semana',
    free: 'Libre', days: 'días', more: 'más',
  },
  en: {
    dashboard: 'Dashboard', employees: 'Employees', attendance: 'Attendance',
    payroll: 'Payroll', overtime: 'Overtime', requests: 'Requests',
    schedule: 'Schedule', reports: 'Reports', users: 'Users',
    departments: 'Departments', onboarding: 'Onboarding', settings: 'Settings',
    general: 'General', localization: 'Localization', security: 'Security',
    profile: 'My Profile', login: 'Sign In', logout: 'Sign Out',
    save: 'Save', cancel: 'Cancel', add: 'Add', edit: 'Edit',
    delete: 'Delete', search: 'Search', filter: 'Filter', export: 'Export',
    total: 'Total', approved: 'Approved', pending: 'Pending', rejected: 'Rejected',
    active: 'Active', inactive: 'Inactive', welcome: 'Welcome back',
    totalEmployees: 'Total Employees', pendingRequests: 'Pending Requests',
    monthlyPayroll: 'Monthly Payroll', activeUsers: 'Active Users',
    thisMonth: 'this month', newToday: 'new today', overtimeHours: 'Overtime Hours',
    byDepartment: 'By Department', byUser: 'By User', totalHours: 'Total Hours',
    approvedRequests: 'Approved Requests', vacationDays: 'Vacation Days',
    recentActivity: 'Recent Activity', shifts: 'Shifts', generateAI: 'Generate with AI',
    weeklyHours: 'Hours this week', language: 'Language',
    name: 'Name', email: 'Email', role: 'Role', area: 'Area', status: 'Status',
    actions: 'Actions', date: 'Date', time: 'Time', type: 'Type',
    description: 'Description', attachment: 'Attachment', download: 'Download',
    close: 'Close', confirm: 'Confirm', back: 'Back', next: 'Next',
    previous: 'Previous', loading: 'Loading', noData: 'No data',
    employee: 'Employee', department: 'Department', position: 'Position',
    phone: 'Phone', address: 'Address', startDate: 'Start Date',
    salary: 'Salary', contract: 'Contract', documents: 'Documents',
    personalInfo: 'Personal Info', payrollInfo: 'Payroll Info',
    history: 'History', notes: 'Notes',
    dailyRecords: 'Daily Records', liveStats: 'Live Stats',
    onTime: 'On Time', late: 'Late', absent: 'Absent', present: 'Present',
    checkIn: 'Check In', checkOut: 'Check Out', workedHours: 'Worked Hours',
    rules: 'Rules', costSimulator: 'Cost Simulator',
    baseRate: 'Base Hourly Rate', ruleToSimulate: 'Rule to Simulate',
    hoursWorked: 'Hours Worked', regularPay: 'Regular Pay',
    surcharge: 'Surcharge', grossTotal: 'Gross Total', result: 'Result',
    configuredRules: 'Configured Rules', newRule: 'New Rule',
    daytime: 'Daytime', nighttime: 'Nighttime', sunday: 'Sunday',
    multiplier: 'Multiplier', shiftType: 'Shift Type',
    liquidation: 'Liquidation', payrollHistory: 'Payroll History',
    baseSalary: 'Base Salary', deductions: 'Deductions', netPay: 'Net Pay',
    bonus: 'Bonus', socialSecurity: 'Social Security',
    approve: 'Approve', reject: 'Reject', medical: 'Medical',
    vacation: 'Vacation', personal: 'Personal', remote: 'Remote',
    training: 'Training', requestType: 'Request Type',
    shiftSchedule: 'Shift Schedule', yearView: 'Year view',
    dragToCreate: 'Drag over days to create shifts',
    morning: 'Morning', afternoon: 'Afternoon', night: 'Night',
    assignedShifts: 'Assigned Shifts', activeEmployees: 'Active Employees',
    coverage: 'Coverage', uncovered: 'Uncovered', dayDetail: 'Day detail',
    people: 'People', hours: 'Hours', noShifts: 'No shifts',
    assignedShiftsList: 'Assigned shifts', createShift: 'Create Shift',
    selectEmployee: 'Select...', shiftTypeLabel: 'Shift Type',
    generateWithAI: 'Generate with AI', applysuggestion: 'Apply suggestion',
    discard: 'Discard', optimizationGoal: 'Optimization Goal',
    optimizeByCost: 'Optimize by cost', reduceOpCosts: 'Reduce operational costs',
    shiftEquity: 'Shift equity', fairDistribution: 'Fair hour distribution',
    seniorityPriority: 'Seniority priority', preferSeniors: 'Prefer senior staff',
    constraints: 'Constraints', minRestHours: 'Min. rest hours',
    minRestDesc: 'Minimum interval between consecutive shifts.',
    avoidOvertime: 'Avoid overtime', generating: 'Generating...',
    estimatedTime: 'Estimated time: ~15 seconds',
    previewWeek: 'Preview: Week 42',
    equity: 'Equity', cost: 'Cost',
    shiftsGenerated: 'Shifts generated successfully with AI',
    shiftsApplied: 'Shifts applied to calendar',
    overview: 'Overview', trends: 'Trends', analytics: 'Analytics',
    custom: 'Custom', monthly: 'Monthly', weekly: 'Weekly',
    daily: 'Daily', annual: 'Annual',
    overtimeByDept: 'Overtime by Department',
    topOvertimeUsers: 'Top Overtime by User',
    monthlyTrend: 'Monthly Trend',
    rolesPermissions: 'Roles & Permissions', auditLog: 'Audit Log',
    createUser: 'Create User', editUser: 'Edit User',
    lastAccess: 'Last Access', createdAt: 'Created',
    permission: 'Permission', module: 'Module',
    addDepartment: 'Add Department', editDepartment: 'Edit Department',
    manager: 'Manager', employeeCount: 'Employees',
    step: 'Step', personalData: 'Personal Data', documentation: 'Documentation',
    bankInfo: 'Bank Info', review: 'Review',
    fullName: 'Full Name', idNumber: 'ID Number',
    birthDate: 'Date of Birth', gender: 'Gender',
    emergencyContact: 'Emergency Contact',
    bankName: 'Bank', accountNumber: 'Account Number',
    accountType: 'Account Type', uploadDocuments: 'Upload Documents',
    timezone: 'Timezone', currency: 'Currency', dateFormat: 'Date Format',
    twoFactorAuth: 'Two-Factor Authentication',
    passwordPolicy: 'Password Policy', sessionTimeout: 'Session Timeout',
    companyName: 'Company Name', companyLogo: 'Company Logo',
    primaryColor: 'Primary Color', notifications: 'Notifications',
    myProfile: 'My Profile', changePassword: 'Change Password',
    currentPassword: 'Current Password', newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    mySchedule: 'My Schedule', myRequests: 'My Requests',
    newRequest: 'New Request', submitRequest: 'Submit Request',
    requestSent: 'Request submitted successfully',
    allModules: 'All modules', employeePortal: 'Employee Portal',
    diurnal: 'Daytime', nocturnal: 'Nighttime', totalCost: 'Total Cost',
    shiftsMonth: 'Shifts/Month', approvedH: 'Approved',
    pendingH: 'pending', year: 'Year', week: 'Week',
    free: 'Free', days: 'days', more: 'more',
  },
}

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'es')

  const setLang = useCallback((l) => {
    localStorage.setItem('lang', l)
    setLangState(l)
  }, [])

  const t = useCallback((key) => translations[lang]?.[key] || translations.es[key] || key, [lang])

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
